# Generated by Django 5.1.5 on 2025-01-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_smslog_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
